spring:
  profiles:
    include: db
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
server:
  port: 8080
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:mapping/*.xml
logging:
  level:
    root: info
    com.jkk.leave.mapper: debug

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql