spring:
  profiles:
    include: db
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8080
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:mapping/*.xml
logging:
  level:
    root: info
    com.jkk.leave.mapper: debug

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
prop:
  upload: F:\webUpload\
  img: F:\webUpload\img\